easy_admin:
    site_name: 'Administración de Colas'
    entities:
      TipoCola:
        class: App\Entity\TipoCola
      Cola:
        class: App\Entity\Cola
        form:
                fields:
                    - { property: 'nombre', type: 'text', type_options: { required: true } }
                    - { property: 'tipo', type_options: { class: 'App\Entity\TipoCola' } }

      Turno:
        class: App\Entity\Turno

    user:
        display_name: true
        name_property_path: 'email'
        display_avatar: false

#- { property: 'category', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }