easy_admin:
    site_name: 'Administrador'
    design:
        menu:            
            - TipoCola
            - { entity: 'Cola', label: 'Colas', icon: 'share' }
            - { entity: 'Turno', label: 'Turnos', icon: 'clock' }
            - { entity: 'Usuario', icon: 'user' }
    entities:
      TipoCola:
        class: App\Entity\TipoCola
      Cola:
        class: App\Entity\Cola
        form:
                fields:
                    - { property: 'nombre', type: 'text', type_options: { required: true } }
                    - { property: 'tipo', type_options: { class: 'App\Entity\TipoCola' } }

      Turno:
        class: App\Entity\Turno
        disabled_actions: ['show','new','edit','delete']

      Usuario:
        class: App\Entity\User
        disabled_actions: ['new']
        form:
                fields:
                    - { property: 'email', type: 'email', type_options: { required: true } }
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                            mapped: true
                            expanded: true
                            multiple: true
                            choices: { 'Usuario': 'ROLE_USER', 'Administrador': 'ROLE_ADMIN' }
        list:
                fields:
                        - 'id'
                        - 'email'
                        - 'roles'
        
    user:
        display_name: true
        name_property_path: 'email'
        display_avatar: false

#- { property: 'category', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }